# Generated by Django 6.0.3 on 2026-04-11 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('SN_COM_FOLHA', 'Simples Nacional com Folha'), ('SN_SEM_FOLHA', 'Simples Nacional sem Folha'), ('MEI', 'MEI'), ('LUCRO_PRESUMIDO', 'Lucro Presumido')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Obrigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('OK', 'ok')], default='PENDENTE', max_length=10)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competencia')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('obrigacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.obrigacao')),
            ],
        ),
    ]
