# Generated by Django 6.0.3 on 2026-04-16 01:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencia',
            options={'ordering': ['-ano', '-mes']},
        ),
        migrations.AddField(
            model_name='empresa',
            name='atualizada_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarefa',
            name='atualizada_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de atualização'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de criação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='core.competencia'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='obrigacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='core.obrigacao'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('OK', 'Concluído')], default='PENDENTE', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='competencia',
            unique_together={('mes', 'ano')},
        ),
        migrations.AlterUniqueTogether(
            name='tarefa',
            unique_together={('empresa', 'competencia', 'obrigacao')},
        ),
    ]
