# Generated by Django 6.0.3 on 2026-04-16 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_competencia_options_empresa_atualizada_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEmpresaObrigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_empresa', models.CharField(choices=[('SN_COM_FOLHA', 'Simples Nacional com Folha'), ('SN_SEM_FOLHA', 'Simples Nacional sem Folha'), ('MEI', 'MEI'), ('LUCRO_PRESUMIDO', 'Lucro Presumido')], max_length=20)),
                ('obrigacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.obrigacao')),
            ],
            options={
                'unique_together': {('tipo_empresa', 'obrigacao')},
            },
        ),
    ]
