# Generated by Django 6.0.3 on 2026-04-16 04:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tipoempresaobrigacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obrigacao',
            name='atualizada_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de atualização'),
        ),
        migrations.AddField(
            model_name='obrigacao',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obrigacao',
            name='dia_vencimento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipoempresaobrigacao',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de criação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='atualizada_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de atualização'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='tipoempresaobrigacao',
            name='obrigacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_empresa', to='core.obrigacao'),
        ),
    ]
