# Generated by Django 6.0.3 on 2026-04-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_competencia_criada_em_obrigacao_atualizada_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='concluida_em',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída'), ('DISPENSADA', 'Dispensada')], default='PENDENTE', max_length=20),
        ),
    ]
